### ISSUE TITLE
make public

### ISSUE THREAD

**Issue by Tieske** [Kong/kong-ci#5]
is there a reason this repo is private? I didn't see anything that looks private to me, so might as well make it publicly available.

Will be necessary when adding it to public plugin repo's anyway

**Comment by Tieske** [comment]
[this](https://github.com/Kong/kong-pongo/pull/35#issuecomment-567038123) suggests people are already using Pongo for CI/CD purposes. It's a goal for Pongo to be able to be used for CI, we just didn't get around to that yet.

So maybe we should not open this up after all? to prevent supporting multiple repo's

**Comment by gszr** [comment]
This has been done, closing this issue.
